[package]
name = "hello_cargo"
version = "0.1.0"
authors = ["GabrielRmoore <47907204+GabrielRmoore@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
